services:
  - type: web
    name: nekkadam
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server_pg.cjs
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.quzmtmvymlrwprewszkr:nekkadam2026@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
